# Data Center ID
datacenter_id: ${DW_DATACENTER_ID:-1}

# Unique Worker ID
worker_id: ${DW_WORKER_ID:-1}

# Validate the User-Agent header?
validate_user_agent: true

# Swagger-specific options.
swagger:

  resourcePackage: com.smoketurner.snowizard.application.resources
  title: Snowizard API
  version: v1
  description: Snowizard service API
  contact: jplock@smoketurner.com
  license: BSD
  licenseUrl: http://opensource.org/licenses/BSD-3-Clause

# HTTP-specific options.
server:

  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: ${PORT:-8080}

  requestLog:
    appenders:
      - type: console
        timeZone: UTC
        target: stdout

logging:
  level: INFO
  loggers:
    com.smoketurner.snowizard: DEBUG
  appenders:
    - type: console
      timeZone: UTC
      target: stdout
